title: Andrey Pylnev  
description: Backend Developer  
show_downloads: true  
theme: jekyll-theme-minimal 
logo: photo.jpg

author: Andrey Pylnev  
email: andrewgo1133official@gmail.com  
github_username: weezord  
linkedin_username: andrey-pylnev-361507344  

navbar-links:  
  About Me: "#about-me"  
  Education: "#education"  
  Work Experience: "#work-experience"  
  Hard Skills: "#hard-skills"  
  Soft Skills: "#soft-skills"  
  Contacts: "#contacts"  

social_links:  
  Telegram: "https://t.me/weezord"  
  GitHub: "https://github.com/weezord"  
  LinkedIn: "https://www.linkedin.com/in/andrey-pylnev-361507344"  
  Email: "mailto:andrewgo1133official@gmail.com"  

